import Head from "next/head";
import styles from "../styles/Home.module.css";
import Home from "./home";
import axios from "axios";

interface Category {
  _id: string;
  title: string;
}

interface Product {
  _id: string;
  category: string;
}

interface IndexProps {
  categoryList: Category[];
  productList: Product[];
}

export default function Index({ categoryList, productList }: IndexProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <Home categoryList={categoryList} productList={productList} />
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get<Category[]>(
    `${process.env.NEXT_PUBLIC_API_URL}/categories`
  );
  const product = await axios.get<Product[]>(
    `${process.env.NEXT_PUBLIC_API_URL}/products`
  );
  return {
    props: {
      categoryList: res.data ? res.data : [],
      productList: product.data ? product.data : [],
    },
  };
};
